Add elixir via asdf
Also on the side clean up scripts a bit. Unfortunately it's not possible
to set the -u option in the setup script... (underlying scripts aren't
save for unbound vars...).

Also: rename bin scripts so that they make more sense.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,82 +1,50 @@
 #!/bin/bash
-readonly DOTFILES_DIR="$HOME/dotfiles"
+readonly HOMEBREW_URL="https://raw.githubusercontent.com/Homebrew/install/master/install"
+readonly OH_MY_ZSH_URL="https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
+readonly MACOS_DEFAULTS="$HOME/dotfiles/scripts/macos.sh"
 
-insert_blank_line() {
-  echo
+# exit immediately if a command exits with non-zero
+set -e
+
+. "$HOME/dotfiles/scripts/print.sh"
+
+update_shell() {
+  local shell_path="/usr/local/bin/zsh"
+  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
+    info "Adding '$shell_path' to /etc/shells"
+    sudo sh -c "echo $shell_path >> /etc/shells" 2>&1 \
+      | print_info
+  fi
+  sudo chsh -s "$shell_path" "$USER" 2>&1 \
+    | print_info
+  success "Using zsh from homebrew"
 }
 
-is_symlink() {
-  local file_name=$1
-  [ -h "$file_name" ]
+set_defaults() {
+  source $MACOS_DEFAULTS 2>&1 | print_info
+  success "Set macOS defaults"
 }
 
-file_exists() {
-  local file_name=$1
-  [ -e "$file_name" ]
+set_computername() {
+  user "How should this computer be called?"
+  read -e name
+  sudo scutil --set ComputerName "$name"
+  sudo scutil --set LocalHostName "$name"
+  success "Set computername to $name"
 }
 
-remove_old_link() {
-  local file=$1
-  is_symlink "$file" &&
-  echo -e "\tRemoving old symlink for $file..." &&
-  rm -rf "$file"
+install_oh_my_zsh() {
+  if [ ! -d "$HOME/.oh-my-zsh" ]; then
+    info "Installing OH MY ZSH"
+    sh -c "$(curl -fsSL $OH_MY_ZSH_URL)"
+  fi
+  success "OH MY ZSH installed"
 }
 
-is_file() {
-  local file=$1
-  file_exists "$file" || return 0
-  echo -e "\tWARNING: $file is a not a symlink! Please remove by hand..." &&
-  return 1
-}
-
-link_files() {
-  local target=$1
-  local link=$2
-
-  remove_old_link "$link" || is_file "$link" &&
-  ln -s "$target" "$link" &&
-  echo -e "\tLinking $link to $target..."
-}
-
-prompt_user() {
-  local question=$1
-  local response
-  insert_blank_line
-  read -rp "Symlink $question? [y|n] " response
-  [ "$response" != "n" ]
-}
-
-symlink() {
-  local targets=$1
-  local link_path=$2
-  for target in $targets; do
-    link_files "$DOTFILES_DIR/$target" "$link_path$(basename "$target")"
-  done
-}
-
-main() {
-  prompt_user "dotfiles for ~/" &&
-  symlink "home/*" "$HOME/."
-
-  prompt_user "Atom Editor config" &&
-  symlink "atom/*" "$HOME/.atom/"
-
-  prompt_user "LaunchD Agents" &&
-    for target in agents/*.plist; do
-      prompt_user "$target" &&
-      symlink "$target" "$HOME/Library/LaunchAgents/"
-    done
-
-  prompt_user "Spectacle shortcuts" &&
-  symlink "config/Spectacle" "$HOME/Library/Application Support/"
-
-  prompt_user "Karabiner config" &&
-  symlink "config/karabiner" "$HOME/.config/"
-
-  prompt_user "Neovim config" &&
-  symlink "config/nvim" "$HOME/.config/"
-
-  prompt_user "ssh config" &&
-  symlink "ssh/config" "$HOME/.ssh/"
-}
-main
+. "$HOME/dotfiles/scripts/homebrew.sh"
+update_shell
+set_defaults
+set_computername
+. "$HOME/dotfiles/scripts/asdf.sh"
+install_oh_my_zsh
+. "$HOME/dotfiles/scripts/neovim.sh"
